export const INITIALIZE_BARS = 'INITIALIZE_BARS';
export const SELECT_BAR = 'SELECT_BAR';
export const CHANGE_SELECTED_BAR_VALUE = 'CHANGE_SELECTED_BAR_VALUE';

export const INITIALIZE_BUTTONS = 'INITIALIZE_BUTTONS';

export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
export const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED';